# Title shown in Application Information tab.
title: Sample Marketplace Stack / ORM Application - BYOL
# Sub Title shown in Application Information tab.
description: This is a Sample Marketplace Stack / ORM Application - BYOL
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=71617800

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: marketplace
  reference: 12345

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
#"variables used internally - not exposed to end user"
      - tenancy_ocid
      - region
      - mp_listing_id
      - mp_listing_resource_id
      - mp_listing_resource_version
      - availability_domain_number
      - mp_subscription_enabled
      - network_strategy_enum
      - subnet_type_enum
      - nsg_config_enum
      #change compute.tf and move custom_image_id to Compute group in case you want to use a custom_image
      - custom_image_id
      - marketplace_source_images

  - title: "Compute Configuration"
    variables:
      - compute_compartment_ocid
      - vm_display_name
      - hostname_label
      - vm_compute_shape
      - vm_flex_shape_ocpus
      - availability_domain_name
      - ssh_public_key


  - title: "Virtual Cloud Network"
    variables:
      - network_compartment_ocid
      - network_strategy
      - network_configuration_strategy
      - vcn_id
      - vcn_display_name
      - vcn_dns_label
      - vcn_cidr_block

  - title: "Simple Subnet"
    visible: #($network_strategy  == ""Use Existing VCN and Subnet"") OR (network_configuration_strategy ==  "Customize Network Configuration")
      or:
        - eq:
          - network_strategy
          - "Use Existing VCN and Subnet"
        - eq:
          - network_configuration_strategy
          - "Customize Network Configuration"
    variables:
      - subnet_type
      - subnet_id
      - subnet_display_name
      - subnet_dns_label
      - subnet_cidr_block
      - nsg_configuration_strategy

  - title: "Network Security Group"
    visible: #($nsg_configuration_strategy  ==  "Customize Network Security Group")
      eq:
        - nsg_configuration_strategy
        - "Customize Network Security Group"
    variables:
      - nsg_display_name
      - nsg_source_cidr
      - nsg_ssh_port
      - nsg_http_port
      - nsg_https_port

  - title: "Additional Configuration Options"
    variables:
      - tag_key_name
      - tag_value


######################################################
##############          VARIABLES        #############
######################################################

variables:
  # Hidden variables

######################################################
##############    HIDDEN VARIABLES       #############
######################################################


  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  availability_domain_number:
    type: string
    required: false
    description: Availability Domain Number (Not used)

######################################################
##############   MARKETPLACE VARIABLES   #############
######################################################

  mp_listing_id:
    type: string
    required: true
    description: Marketplace Listing ID

  mp_listing_resource_id:
    type: oci:core:image:id
    required: true
    description: Marketplace Image OCID
    dependsOn:
      compartmentId: compute_compartment_ocid

  mp_listing_resource_version:
    type: string
    required: true
    description: Marketplace Listing package version


  mp_subscription_enabled:
    type: boolean
    title: Use Marketplace Image?
    default: false

  custom_image_id:
    type: string
    required: true
    title: Custom Image OCID
    # visible:
    #   eq:
    #     - mp_subscription_enabled
    #     - false


  tag_key_name:
    type: string
    required: true
    title: Tag key name

  tag_value:
    type: string
    required: true
    title: Tag value


######################################################
##############    COMPUTE VARIABLES      #############
######################################################

  compute_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compute Compartment
    description: The compartment in which to create all Compute resources
    default: compartment_ocid

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compute_compartment_ocid
    required: true
    default: 1
    title: Availability Domain
    description: Availability Domain

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: Public SSH Key string
    description: Public SSH Key to access VM via SSH

  vm_display_name:
    type: string
    required: true
    title: Instance Name
    description: The name of the Instance

  vm_compute_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.2
    title: Compute Shape
    required: true
    dependsOn:
      compartmentId: compute_compartment_ocid
      #Comment in to restrict to marketplace image allowed shapes 
      #imageId: mp_listing_resource_id

  vm_flex_shape_ocpus:
    visible: #($vm_compute_shape  == ""VM.Standard.E3.Flex"")
      eq:
        - vm_compute_shape
        - "VM.Standard.E3.Flex"
    type: integer
    default: 2
    title: Flex Shape OCPUs
    minimum: 1
    maximum: 64
    required: false

  hostname_label:
    type: string
    required: false
    title: DNS Hostname Label


######################################################
##############     NETWORK VARIABLES     #############
######################################################

  network_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Network Compartment
    description: The compartment in which to create all Network resources
    default: compartment_ocid


  # Network Type Options
  network_strategy:
    type: enum
    title: Network Strategy
    description: Create or use existing Network Stack (VCN and Subnet)
    enum:
      - "Create New VCN and Subnet"
      - "Use Existing VCN and Subnet"
    required: true
    default: "Create New VCN and Subnet"


  # Network Configuration
  network_configuration_strategy:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy
        - "Create New VCN and Subnet"
    type: enum
    title: Configuration Strategy
    description: Use recommended configuration or customize it
    enum:
      - "Use Recommended Configuration"
      - "Customize Network Configuration"
    required: true
    default: "Use Recommended Configuration"



######## VCN ########

  vcn_display_name:
    visible: #($network_strategy  == ""Create New VCN and Subnet"") AND (network_configuration_strategy ==  "Customize Network Configuration")
      and:
        - eq:
          - network_strategy
          - "Create New VCN and Subnet"
        - eq:
          - network_configuration_strategy
          - "Customize Network Configuration"
    type: string
    required: true
    title: Name
    description: The name of the new Virtual Cloud Network (VCN)

  vcn_id:
    visible: #($network_strategy  == "Use Existing VCN and Subnet")
      eq:
        - network_strategy
        - "Use Existing VCN and Subnet"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: network_compartment_ocid
    required: true
    title: Existing VCN
    description: An existing Virtual Cloud Network (VCN) in which to create the compute instances, network resources, and load balancers. If not specified, a new VCN is created.

  vcn_cidr_block:
    visible: #($network_strategy  == ""Create New VCN and Subnet"") AND (network_configuration_strategy ==  "Customize Network Configuration")
      and:
        - eq:
          - network_strategy
          - "Create New VCN and Subnet"
        - eq:
          - network_configuration_strategy
          - "Customize Network Configuration"
    type: string
    required: true
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: CIDR Block
    description: The CIDR of the new Virtual Cloud Network (VCN). If you plan to peer this VCN with another VCN, the VCNs must not have overlapping CIDRs.

  vcn_dns_label:
    visible: #($network_strategy  == ""Create New VCN and Subnet"") AND (network_configuration_strategy ==  "Customize Network Configuration")
      and:
        - eq:
          - network_strategy
          - "Create New VCN and Subnet"
        - eq:
          - network_configuration_strategy
          - "Customize Network Configuration"
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: VCN DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

######## MANAGEMENT SUBNET ########
  subnet_type:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy
        - "Create New VCN and Subnet"
    type: enum
    title: Subnet Type
    description: Choose between private and public subnets
    enum:
      - "Private Subnet"
      - "Public Subnet"
    required: true
    default: "Public Subnet"

  subnet_display_name:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy
        - "Create New VCN and Subnet"
    type: string
    required: true
    title: Name
    description: The name of the new Subnet

  subnet_cidr_block:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy
        - "Create New VCN and Subnet"
    type: string
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: CIDR Block
    description: The CIDR of the new Subnet. The new subnet's CIDR should not overlap with any other subnet CIDRs.

  subnet_id:
    visible: #($network_strategy  == "Use Existing VCN and Subnet")
      eq:
        - network_strategy
        - "Use Existing VCN and Subnet"
    type: oci:core:subnet:id
    dependsOn:
      vcnId: vcn_id
      compartmentId: network_compartment_ocid
    default: ''
    required: true
    title: Existing Subnet
    description: An existing Management subnet. This subnet must already be present in the chosen VCN.

  subnet_dns_label:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy
        - "Create New VCN and Subnet"
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: Subnet DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

######################################################
##############    SECURITY VARIABLES     #############
######################################################


  nsg_configuration_strategy:
    visible: true
    type: enum
    title: Network Security Group Configuration
    description: Choose Network Security Rules Strategy
    enum:
      - "Use Recommended Configuration"
      - "Customize Network Security Group"
    required: true
    default: "Use Recommended Configuration"


  nsg_display_name:
    type: string
    required: false
    title: Name

  nsg_ssh_port:
    type: number
    required: false
    default: 22
    title: SSH Port Number

  nsg_http_port:
    type: number
    required: false
    default: 80
    title: HTTP Port Number

  nsg_https_port:
    type: number
    required: false
    default: 443
    title: HTTPS Port Number

  nsg_source_cidr:
    type: string
    required: false
    default: "0.0.0.0/0"
    title: Allowed Ingress Traffic (CIDR Block)




#############################################
###########    OUTPUT GROUPS     ############
#############################################

outputGroups:
  - title: "Instance Management"
    outputs:
      - instance_public_ip
      - instance_private_ip


#############################################
##############     OUTPUTS     ##############
#############################################

outputs:
  instance_https_url:
    type: link
    title: Open Application URL
    visible: false

  instance_public_ip:
    type: link
    title: Public IP
    visible: #($mgmt_subnet_type == "Public Subnet")
      eq:
      - mgmt_subnet_type
      - "Public Subnet"

  instance_private_ip:
    type: link
    title: Private IP
    visible: true

primaryOutputButton: instance_https_url
