# ####################################################################################################### #
# Copyright (c) 2023 Oracle and/or its affiliates,  All rights reserved.                                  #
# Licensed under the Universal Permissive License v 1.0 as shown at https: //oss.oracle.com/licenses/upl. #
# Author: Cosmin Tudor                                                                                    #
# Author email: cosmin.tudor@oracle.com                                                                   #
# Last Modified: Thu Nov 16 2023                                                                          #
# Modified by: Cosmin Tudor, email: cosmin.tudor@oracle.com                                               #
# ####################################################################################################### #


title: "OCI OPEN LANDING ZONE ORM STACK"
stackDescription: "Creates and changes elements of the OCI Open Landing Zone."
description: ""
schemaVersion: 1.1.0
version: "0.0.1"
locale: "en"

# URL of CIS Landing Zone logo icon used on Application Information tab.
logoUrl: "https://objectstorage.us-ashburn-1.oraclecloud.com/p/taf6kC9fSJyQDNSYbxvqxS_JsdnSu56oFZ3-1h5vI7-WfJUv77mplChopLxZPePW/n/ociateam/b/cis-landing-zone/o/landing_zone_130.png"

variableGroups:
  - title: "INPUT JSON AND/OR YAML CONFIGURATION FILES URLS"
    visible: true
    variables:
      - input_config_files_urls
  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "private_key_password"
      - "region"
      - "home_region"
variables:
  input_config_files_urls:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: Type or Paste the URLs
    additionalProps:
        allowMultiple: true
    description: "Only JSON files accepted - HCL not supported yet"
    required: false

outputs:
  release:
    type: string
    title: OCI Open Landing Zone

  region:
    type: string
    title: Region

  provisioned_identity_resources:
    type: json
    title: Provisioned Identity Resources

  provisioned_networking_resources:
    type: json
    title: Provisioned Networking Resources 

outputGroups:
  - title: Environment
    outputs:
      - ${release}
      - ${region}

  - title: Identity Resources
    outputs:
      - ${provisioned_identity_resources}    

  - title: Neworking Resources
    outputs:
      - ${provisioned_networking_resources}    
