CREATE USER FINOPS IDENTIFIED BY "<password>";
GRANT CONNECT,DWROLE,RESOURCE TO FINOPS;
ALTER USER FINOPS DEFAULT ROLE CONNECT,DWROLE,RESOURCE;
ALTER USER FINOPS quota unlimited on DATA;

--Enable Resource principal for the created user
EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL(username => 'FINOPS')